/* UE 10 — Comptabilité approfondie (programme réformé, session 2027 ; PCG modifié par le règlement ANC 2022-06) */
(function () {
  var C = window.DCG_CARDS, Q = window.DCG_QCM;
  var PCG25 = "PCG 2025 (règlement ANC 2022-06), exercices ouverts à compter du 01/01/2025";

  C.push(
    // ========== 1. Cadre normatif ==========
    { id: 'ue10-101', ue: 10, q: "Quel est le cadre normatif des comptes individuels en France ?", a: "Le plan comptable général (règlement ANC n° 2014-03, modifié notamment par le règlement ANC n° 2022-06 applicable aux exercices ouverts à compter du 1er janvier 2025), établi par l'Autorité des normes comptables (ANC), complété par les dispositions du Code de commerce (art. L123-12 s.) et les avis et recommandations de l'ANC.", d: PCG25 },
    { id: 'ue10-102', ue: 10, q: "Que change la réforme du PCG applicable en 2025 ?", a: "Un plan de comptes unique (schéma de base) avec environ 150 comptes supprimés ; deux nouveaux modèles de bilan et de compte de résultat ; une nouvelle définition (restrictive) du résultat exceptionnel ; la suppression de la technique des transferts de charges ; une annexe enrichie de tableaux normés ; la modernisation des états financiers.", d: PCG25 },
    { id: 'ue10-06', ue: 10, q: "Principes comptables fondamentaux ?", a: "Prudence, continuité d'exploitation, permanence des méthodes, indépendance des exercices, intangibilité du bilan d'ouverture, coût historique, non-compensation, image fidèle (régularité, sincérité)." },
    { id: 'ue10-01', ue: 10, q: "Principe d'indépendance des exercices ?", a: "Chaque exercice comptabilise uniquement ses charges et produits : on enregistre les charges constatées d'avance, produits constatés d'avance, factures non parvenues (charges à payer) et produits à recevoir." },
    { id: 'ue10-02', ue: 10, q: "Principe de prudence ?", a: "Ne pas comptabiliser de produits non réalisés, mais provisionner les risques et pertes probables (dépréciations, provisions) ; les gains latents ne sont pas constatés." },
    { id: 'ue10-103', ue: 10, q: "Quelles sont les règles d'évaluation à l'entrée et à l'inventaire ?", a: "Entrée : coût d'acquisition ou de production (coût historique) ; actifs reçus à titre gratuit : valeur vénale. Inventaire : comparaison de la valeur nette comptable à la valeur actuelle (valeur d'inventaire) ; amortissement et dépréciation si besoin." },
    { id: 'ue10-104', ue: 10, q: "Qu'est-ce que la nouvelle définition du résultat exceptionnel ?", a: "Depuis les exercices ouverts en 2025, le résultat exceptionnel ne retrace que les produits et charges directement liés à un événement majeur, inhabituel et rare (ex. sinistre majeur, restructuration importante). Les éléments récurrents ou courants (cessions courantes d'immobilisations) en sortent.", d: PCG25 },
    { id: 'ue10-105', ue: 10, q: "Que deviennent les transferts de charges avec le PCG 2025 ?", a: "Les comptes 791, 796 et 797 sont supprimés. On comptabilise selon la nature de l'opération : refacturations en 708, remboursements de charges de personnel en 649, indemnités d'assurance en 7587, aides à l'emploi en 741, etc.", d: PCG25 },
    { id: 'ue10-106', ue: 10, q: "Quels sont les états financiers et leur nouvelle présentation ?", a: "Bilan, compte de résultat (présentation en liste, par nature) et annexe. Avec le règlement ANC 2022-06 : deux modèles de bilan et de compte de résultat remplacent les modèles de base, abrégé et développé ; un seul plan de comptes (comptes obligatoires et facultatifs).", d: PCG25 },
    { id: 'ue10-107', ue: 10, q: "Quels seuils pour les catégories d'entreprises en comptabilité ?", a: "Micro-entité : bilan < 450 000 €, CA < 900 000 €, moins de 10 salariés. Petite entreprise : bilan 7,5 M€, CA 15 M€, 50 salariés. Moyenne : 25 M€, 50 M€, 250 salariés. Deux critères sur trois, sur 2 exercices consécutifs ; ces catégories déterminent les obligations (annexe simplifiée, publicité).", d: "Seuils relevés (directive (UE) 2023/2775, décret n° 2024-152), exercices ouverts depuis le 01/01/2024 — à confirmer" },

    // ========== 2. Actif : immobilisations ==========
    { id: 'ue10-07', ue: 10, q: "Qu'est-ce qu'une immobilisation (PCG) ?", a: "Un actif identifiable (séparable ou issu de droits légaux/contractuels), contrôlé par l'entité, destiné à servir de façon durable (plus d'un exercice) et dont on attend des avantages économiques futurs. Les petites valeurs peuvent être passées en charges." },
    { id: 'ue10-08', ue: 10, q: "Coût d'entrée d'une immobilisation acquise ?", a: "Prix d'achat net des remises et rabais + droits de douane et taxes non récupérables + coûts directement attribuables (transport, installation, honoraires). Option pour les frais d'acquisition (droits de mutation, honoraires, commissions) : charges ou incorporation au coût. Immobilisation produite : coût de production." },
    { id: 'ue10-108', ue: 10, q: "Frais de recherche et de développement : comment les traiter ?", a: "Frais de recherche : en charges. Frais de développement : immobilisables (compte 203) si le projet est distinct, techniquement faisable, rentable et si l'entité a la volonté d'achever le projet et de l'utiliser ou de le vendre ; sinon en charges." },
    { id: 'ue10-109', ue: 10, q: "Que comprend le coût de production d'une immobilisation créée ?", a: "Coût d'acquisition des matières, charges directes de production et quote-part des charges indirectes de production, hors charges de sous-activité ; option pour les intérêts d'emprunt finançant la production (jusqu'à la mise en service)." },
    { id: 'ue10-09', ue: 10, q: "Approche par composants ?", a: "Chaque élément d'une immobilisation ayant une durée d'utilisation différente (ou procurant des avantages économiques à un rythme différent) est comptabilisé et amorti séparément (ex. gros œuvre, toiture, ascenseur d'un immeuble)." },
    { id: 'ue10-110', ue: 10, q: "Comment traite-t-on les dépenses ultérieures sur une immobilisation ?", a: "Dépenses d'entretien : charges. Dépenses améliorant la durée de vie, la capacité ou la performance : immobilisées. Grosses réparations ou grandes révisions : composant amorti sur la période jusqu'à la prochaine révision, ou provision pour gros entretien." },
    { id: 'ue10-111', ue: 10, q: "Comment comptabilise-t-on une immobilisation reçue en échange ou en apport ?", a: "Apport : valeur d'apport figurant dans l'acte (valeur vénale en principe). Échange : le bien reçu est comptabilisé à la valeur vénale du bien cédé ; une soulte éventuelle est prise en compte. Acquisition à titre gratuit : valeur vénale." },
    { id: 'ue10-10', ue: 10, q: "Amortissement linéaire : formule et prorata temporis ?", a: "Annuité = base amortissable ÷ durée d'utilisation (taux = 1 ÷ durée). La première annuité est calculée prorata temporis de la date de mise en service (en mois ou en jours). Base amortissable = coût d'entrée − valeur résiduelle éventuelle." },
    { id: 'ue10-112', ue: 10, q: "Qu'est-ce que la durée d'utilisation et la valeur résiduelle ?", a: "Durée d'utilisation : période pendant laquelle l'entité compte utiliser l'actif (usage prévu, usure, obsolescence). Valeur résiduelle : montant net estimé de cession en fin d'utilisation ; elle réduit la base amortissable si elle est significative et mesurable." },
    { id: 'ue10-11', ue: 10, q: "Coefficients de l'amortissement dégressif ?", a: "1,25 si durée de 3 ou 4 ans · 1,75 si 5 ou 6 ans · 2,25 si plus de 6 ans. Taux dégressif = taux linéaire × coefficient, appliqué à la VNC. On passe au linéaire quand l'annuité linéaire sur la durée restante devient supérieure.", d: "Coefficients fiscaux en vigueur — à confirmer avec ton cours" },
    { id: 'ue10-12', ue: 10, q: "Amortissement dérogatoire : définition et compte ?", a: "Écart entre l'amortissement fiscal (dégressif, exceptionnel) et l'amortissement économique (pour durée d'utilité) : dotation en 68725, reprise en 78725, compte 145 « amortissements dérogatoires » au passif (provisions réglementées). Il est classé en résultat exceptionnel.", d: PCG25 },
    { id: 'ue10-113', ue: 10, q: "Comment modifier un plan d'amortissement ?", a: "Un changement d'estimation (durée d'utilisation, valeur résiduelle, rythme) est appliqué de façon prospective : la VNC est amortie sur la durée restante révisée, sans retraitement du passé. Un changement de méthode d'amortissement est un changement de méthode comptable." },
    { id: 'ue10-114', ue: 10, q: "Fonds commercial : amortissement et dépréciation ?", a: "Le fonds commercial est un actif incorporel. Il est amorti si sa durée d'utilisation est limitée ; sinon non amorti, avec test de dépréciation au moins annuel : dépréciation si la valeur actuelle devient inférieure à la valeur nette comptable (comptes 207 et 2907)." },
    { id: 'ue10-13', ue: 10, q: "Dépréciation d'une immobilisation : quand ?", a: "S'il existe un indice de perte de valeur et que la valeur actuelle (la plus élevée de la valeur vénale et de la valeur d'usage) devient inférieure à la VNC. Dotation en 6816 (68161 immobilisations incorporelles, 68162 corporelles), comptes 29.", d: PCG25 },
    { id: 'ue10-03', ue: 10, q: "Différence entre amortissement et dépréciation ?", a: "L'amortissement constate la perte de valeur certaine et irréversible (usure, obsolescence). La dépréciation constate une perte de valeur probable et réversible." },
    { id: 'ue10-05', ue: 10, q: "Résultat de cession d'une immobilisation ?", a: "Prix de cession − Valeur nette comptable (VNC). Plus-value si positif, moins-value si négatif. VNC = valeur d'origine − amortissements cumulés (− dépréciation éventuelle)." },
    { id: 'ue10-19', ue: 10, q: "Écritures de cession d'une immobilisation (PCG 2025) ?", a: "1) Dotation complémentaire jusqu'à la date de cession (68111/68112). 2) Produit : débit 462 ou 512 / crédit 757 (prix de cession HT) et 44571 (TVA). 3) Sortie : débit 28x (amortissements cumulés) et 657 (VNC) / crédit 2x (valeur d'origine). Avant 2025 : 675 et 775.", d: PCG25 },
    { id: 'ue10-115', ue: 10, q: "Comment traite-t-on la mise au rebut d'une immobilisation ?", a: "Sortie sans contrepartie financière : on annule la valeur d'origine et les amortissements cumulés ; la VNC est une charge (compte 657 depuis 2025, 675 avant) ; une dépréciation éventuelle est reprise.", d: PCG25 },
    { id: 'ue10-116', ue: 10, q: "Comment comptabilise-t-on une immobilisation en cours et une avance sur immobilisation ?", a: "Immobilisation en cours (231 corporelles, 232 incorporelles) tant que le bien n'est pas mis en service, sans amortissement ; avances et acomptes versés (237, 238). Transfert au compte définitif à la mise en service, début de l'amortissement." },
    { id: 'ue10-117', ue: 10, q: "Subvention d'investissement : comptabilisation avec le PCG 2025 ?", a: "Reçue en capitaux propres (131) au moment où le droit est acquis ; sa quote-part est reprise au résultat chaque année au rythme de l'amortissement du bien subventionné : débit 139 / crédit 747 (anciennement 777).", d: PCG25 },

    // ----- Stocks -----
    { id: 'ue10-15', ue: 10, q: "Évaluation et dépréciation des stocks ?", a: "Évaluation au coût d'acquisition ou de production. Sortie : CMUP ou PEPS/FIFO (DEPS/LIFO interdit). Dépréciation si valeur d'inventaire inférieure au coût : comptes 39, dotation 68173 (6817), reprise 78173.", d: "Numérotation PCG 2025 — vérifie les sous-comptes dans ton manuel" },
    { id: 'ue10-16', ue: 10, q: "Variation de stocks de marchandises : sens des écritures ?", a: "Stock initial annulé : débit 6037 / crédit 37. Stock final constaté : débit 37 / crédit 6037. Si SF > SI, 6037 est créditeur (la variation diminue les charges) ; si SF < SI, il est débiteur." },
    { id: 'ue10-118', ue: 10, q: "Qu'est-ce que l'inventaire permanent ?", a: "Système où chaque entrée et sortie de stock est enregistrée au fil de l'eau (comptes 3 mouvementés à chaque opération). À la clôture, on compare l'inventaire physique et la comptabilité pour enregistrer les écarts." },
    { id: 'ue10-119', ue: 10, q: "Comment évalue-t-on le coût de production d'un stock de produits finis ?", a: "Coût d'acquisition des matières consommées + charges directes de production + quote-part des charges indirectes de production (en activité normale) ; sont exclus les frais de distribution, les charges de sous-activité et, en principe, les frais financiers." },
    { id: 'ue10-120', ue: 10, q: "Variations de stocks de produits : quels comptes ?", a: "713 Variation des stocks de produits (en-cours, produits intermédiaires et finis) : crédit si le stock augmente, débit s'il diminue ; 6031 pour matières premières, 6032 pour autres approvisionnements, 6037 pour marchandises." },

    // ----- Actifs financiers et créances -----
    { id: 'ue10-14', ue: 10, q: "Traitement d'un client douteux ?", a: "Reclassement : débit 416 Clients douteux / crédit 411 (TTC). Dépréciation de la perte probable, calculée sur le HT : débit 68174 (6817) / crédit 491. Si perte définitive : débit 654 (HT) et 44571 (TVA) / crédit 416 ; reprise de la dépréciation.", d: PCG25 },
    { id: 'ue10-121', ue: 10, q: "Quelles sont les catégories d'actifs financiers ?", a: "Titres de participation (261, détention durable et contrôle ou influence), autres titres immobilisés et titres immobilisés de l'activité de portefeuille (TIAP), prêts et créances rattachées (27), valeurs mobilières de placement (50), actions propres." },
    { id: 'ue10-122', ue: 10, q: "Comment évalue-t-on et déprécie-t-on les titres de participation ?", a: "Coût d'acquisition (prix + frais accessoires, option). À l'inventaire, comparaison avec la valeur d'utilité (valeur actuelle) : dépréciation (2961) si inférieure au coût ; dotation en résultat financier (686)." },
    { id: 'ue10-123', ue: 10, q: "Comment comptabilise-t-on la cession de titres ?", a: "Les titres sortent au coût d'entrée (méthode du coût moyen pondéré ou PEPS par catégorie) ; le prix de cession est encaissé ou enregistré en créance sur cession (462) ; la plus ou moins-value est comptabilisée en résultat financier. Les numéros de comptes détaillés dépendent du PCG 2025 : vérifie-les dans ton manuel.", d: PCG25 },
    { id: 'ue10-124', ue: 10, q: "Comment traite-t-on les dividendes reçus de filiales et participations ?", a: "Produits financiers : débit 462 ou 512 / crédit 7611 (revenus des titres de participation) lorsque le droit est acquis (décision de l'assemblée). Régime mère-fille : exonération fiscale, avec quote-part de frais et charges réintégrée." },
    { id: 'ue10-125', ue: 10, q: "Comment comptabilise-t-on un prêt accordé et les intérêts courus à recevoir ?", a: "Le prêt accordé est un actif financier (compte 27) avec créance rattachée pour les intérêts. À la clôture, les intérêts courus à recevoir sont rattachés à l'exercice (produit financier) ; une dépréciation est constituée si le recouvrement est incertain." },

    // ----- Régularisations -----
    { id: 'ue10-17', ue: 10, q: "Charges constatées d'avance et produits constatés d'avance ?", a: "CCA : charge payée sur l'exercice mais relative au suivant (compte 486, à l'actif). PCA : produit encaissé d'avance mais relatif au suivant (compte 487, au passif). Régularisées en début d'exercice suivant par extourne." },
    { id: 'ue10-18', ue: 10, q: "Charges à payer et produits à recevoir ?", a: "Charges à payer : factures non parvenues (408 pour des fournisseurs, 4286/4386... pour le personnel et les organismes sociaux). Produits à recevoir : produits acquis mais non encore facturés (418, 4287...)." },

    // ========== 3. Passif ==========
    { id: 'ue10-126', ue: 10, q: "Comment se composent les capitaux propres ?", a: "Capital (101), primes liées au capital (104), écarts de réévaluation (105), réserves (106 : légale 1061, statutaires 1063, réglementées 1064, autres 1068), report à nouveau (11), résultat de l'exercice (12), subventions d'investissement (13), provisions réglementées (14)." },
    { id: 'ue10-23', ue: 10, q: "Augmentation de capital par apports en numéraire : écritures ?", a: "Souscription : débit 456 Associés – opérations sur le capital / crédit 1011 Capital souscrit non appelé (ou 1012, 1013 selon l'appel) et 1041 Prime d'émission. Libération : débit 512 / crédit 456. La contrepartie du capital souscrit non appelé est portée à l'actif en 109 (actionnaires)." },
    { id: 'ue10-127', ue: 10, q: "Augmentation de capital par incorporation de réserves : écriture ?", a: "Débit 106 (réserves) ou 104 (primes) ou 11 / crédit 1013 Capital souscrit, appelé, versé (ou 1011/1012) ; pas d'apport nouveau : le capital augmente par prélèvement sur les réserves, les capitaux propres totaux sont inchangés." },
    { id: 'ue10-128', ue: 10, q: "Réduction de capital motivée par des pertes : écriture ?", a: "Débit 101 (capital) / crédit 119 Report à nouveau (solde débiteur) : le capital est réduit à hauteur des pertes imputées ; les capitaux propres totaux ne changent pas, mais le capital est reconstitué en regard des fonds propres." },
    { id: 'ue10-24', ue: 10, q: "Affectation du résultat : ordre des opérations ?", a: "1) Imputation des pertes antérieures (report à nouveau). 2) Dotation à la réserve légale (5 %, jusqu'à 10 % du capital). 3) Réserves statutaires. 4) Dividendes. 5) Autres réserves. 6) Report à nouveau du solde." },
    { id: 'ue10-25', ue: 10, q: "Écriture de l'affectation du résultat (bénéfice) ?", a: "Débit 120 Résultat de l'exercice (bénéfice) / Crédit 1061 Réserve légale, 457 Associés – dividendes à payer, 1068 Autres réserves, 110 Report à nouveau créditeur. Le paiement des dividendes débite 457 / crédit 512 (retenue éventuelle)." },
    { id: 'ue10-129', ue: 10, q: "Acomptes sur dividendes et rachat d'actions : comment les comptabiliser ?", a: "Acompte sur dividendes versé avant l'approbation des comptes : compte 129 (acompte sur dividendes) en débit au bilan d'ouverture jusqu'à l'affectation. Rachat d'actions propres : titres immobilisés (2771) ou valeurs mobilières (502) avec dépréciation éventuelle ; annulation en réduction de capital." },
    { id: 'ue10-04', ue: 10, q: "Quand constitue-t-on une provision pour risques et charges ?", a: "Quand il existe une obligation à l'égard d'un tiers, dont il est probable ou certain qu'elle provoquera une sortie de ressources sans contrepartie au moins équivalente, et dont le montant est estimable avec fiabilité. Dotation : 6815, reprise : 7815.", d: PCG25 },
    { id: 'ue10-130', ue: 10, q: "Quels sont les principaux types de provisions pour risques et charges ?", a: "Litiges (1511), garanties données aux clients (1512), amendes et pénalités (1518), pensions et obligations similaires (153), impôts (155), renouvellement des immobilisations, gros entretien ou grandes révisions (1572), restructurations. Les passifs éventuels sont mentionnés dans l'annexe." },
    { id: 'ue10-131', ue: 10, q: "Provision pour litige : comment l'enregistrer et la reprendre ?", a: "Dotation : débit 6815 / crédit 1511. À la fin du litige : si la charge est supérieure à la provision, charge complémentaire ; si inférieure, reprise de l'excédent (débit 1511 / crédit 7815). Reprise totale si le risque disparaît." },
    { id: 'ue10-132', ue: 10, q: "Provision pour garantie donnée aux clients et pour charges futures ?", a: "Si l'entreprise s'est engagée à réparer ou remplacer, une provision est constituée dès la vente selon l'expérience (taux de retour). Elle peut aussi porter sur d'autres charges (remise en état de site, démantèlement)." },
    { id: 'ue10-133', ue: 10, q: "Engagements de retraite : provision ou annexe ?", a: "Le PCG recommande la méthode préférentielle : provision pour indemnités de départ à la retraite et avantages similaires (méthode des unités de crédit projetées). Option : ne pas provisionner et mentionner l'engagement en annexe, avec cohérence dans le temps." },
    { id: 'ue10-134', ue: 10, q: "Provision pour gros entretien ou grandes révisions ?", a: "Constituée progressivement pour couvrir une dépense programmée de grandes révisions qui ne sera pas immobilisée comme composant. Dotation en 6815 sur la période entre deux révisions, utilisation à la réalisation de la dépense." },
    { id: 'ue10-135', ue: 10, q: "Comment distinguer provision, dépréciation et dette ?", a: "Dépréciation : perte de valeur d'un actif (diminue l'actif). Provision pour risques et charges : passif dont l'échéance ou le montant est incertain. Dette : passif dont l'échéance et le montant sont certains (ex. facture non parvenue)." },
    { id: 'ue10-136', ue: 10, q: "Emprunt bancaire : comptabilisation de l'encaissement et de l'échéance ?", a: "Encaissement : débit 512 / crédit 164 (emprunts auprès des établissements de crédit), frais éventuels en charges. Échéance : débit 164 (amortissement du capital) et 661 (intérêts) / crédit 512." },
    { id: 'ue10-20', ue: 10, q: "Emprunt : écriture d'intérêts courus à la clôture ?", a: "Débit 661 Charges d'intérêts (6611) / crédit 1688 Intérêts courus sur emprunts (prorata temporis du dernier échéancier). Extourne au début de l'exercice suivant." },
    { id: 'ue10-137', ue: 10, q: "Emprunt obligataire : prime d'émission et prime de remboursement ?", a: "Emprunt obligataire en 163 pour la valeur de remboursement. Prime de remboursement (valeur de remboursement − prix d'émission) : actif 169, amortie sur la durée de l'emprunt (686). Frais d'émission : charge (ou étalement selon option du PCG).", d: "Vérifier le traitement retenu par ton manuel (PCG 2025)" },
    { id: 'ue10-138', ue: 10, q: "Comment est comptabilisé l'amortissement d'un emprunt obligataire ?", a: "Le remboursement du nominal diminue la dette (163). Si amorti in fine : à l'échéance, débit 163 / crédit 512 ; si amorti par tirage au sort ou annuités, chaque remboursement diminue l'encours et les intérêts diminuent. Les intérêts courus sont enregistrés à la clôture." },
    { id: 'ue10-139', ue: 10, q: "Qu'est-ce que la dette fournisseur d'immobilisation et les avances ?", a: "Fournisseurs d'immobilisations (404) : dettes liées à l'acquisition d'immobilisations (hors exploitation). Avances et acomptes reçus (4191), dettes sociales (421, 43), fiscales (44) : toutes enregistrées au passif à leur valeur à la clôture." },

    // ========== 4. Contrats à long terme, impôts, changements comptables ==========
    { id: 'ue10-140', ue: 10, q: "Qu'est-ce qu'un contrat à long terme (CLT) ?", a: "Contrat de fourniture d'un bien ou d'un service dont l'exécution s'étale sur plus d'un exercice (construction, travaux, ingénierie). Deux méthodes de comptabilisation du résultat : à l'avancement (résultat reconnu au fil de l'exécution) ou à l'achèvement (résultat reconnu à la livraison)." },
    { id: 'ue10-141', ue: 10, q: "Méthode à l'avancement : comment calculer le chiffre d'affaires de l'exercice ?", a: "Taux d'avancement = coûts engagés à ce jour ÷ coûts totaux estimés (ou quantités livrées ÷ quantités totales). CA de l'exercice = prix du contrat × taux d'avancement − CA cumulé constaté sur les exercices antérieurs. Le résultat est reconnu au même rythme." },
    { id: 'ue10-142', ue: 10, q: "Perte à terminaison sur un contrat à long terme ?", a: "Si les coûts totaux estimés dépassent le prix du contrat, la perte prévisible (à terminaison) est constatée immédiatement par une provision pour perte à terminaison (principe de prudence), quelle que soit la méthode." },
    { id: 'ue10-143', ue: 10, q: "Comment comptabiliser un contrat à long terme à l'avancement ?", a: "On enregistre à chaque clôture le chiffre d'affaires partiel (compte de produits 70) et les charges correspondantes ; les montants facturés (clients) et non encore acquis donnent lieu à des produits constatés d'avance ou à des factures à établir selon la position." },
    { id: 'ue10-144', ue: 10, q: "Impôt sur les bénéfices : comment le comptabilise-t-on ?", a: "L'IS est un impôt exigible calculé sur le résultat fiscal : débit 695 Impôts sur les bénéfices / crédit 444 État – impôts sur les bénéfices. Les acomptes versés sont débités en 444 ; le solde à payer est le montant restant au crédit du compte 444.", d: "Taux d'IS 2026 : 25 % (15 % jusqu'à 42 500 € pour les PME éligibles)" },
    { id: 'ue10-27', ue: 10, q: "Charge d'impôt sur les sociétés : écritures ?", a: "Acomptes payés : débit 444 / crédit 512. À la clôture : débit 695 / crédit 444 (IS dû). Si les acomptes dépassent l'IS dû : créance sur l'État (444 débiteur, restitution ou imputation). Contribution sociale sur l'IS le cas échéant." },
    { id: 'ue10-145', ue: 10, q: "Impôts différés : faut-il les comptabiliser dans les comptes individuels ?", a: "Non, en principe : les comptes individuels n'enregistrent que l'impôt exigible ; l'impact des décalages entre résultat comptable et résultat fiscal (impôts différés) est donné en annexe. Les impôts différés sont obligatoirement constatés dans les comptes consolidés." },
    { id: 'ue10-146', ue: 10, q: "Comment comptabiliser un crédit d'impôt (CIR, CII) ?", a: "Le crédit d'impôt s'impute sur l'IS dû ; pour la part excédentaire restituable, une créance sur l'État est comptabilisée à l'actif. Selon sa nature, le produit est présenté en diminution de l'impôt ou en subvention d'exploitation." },
    { id: 'ue10-147', ue: 10, q: "Changements comptables : méthode, estimation, erreur ?", a: "Changement de méthode comptable : appliqué de façon rétrospective, avec impact en report à nouveau (réserves). Changement d'estimation : appliqué prospectivement, impact en résultat. Correction d'erreur : rétroactive ; impact en report à nouveau si significatif." },
    { id: 'ue10-148', ue: 10, q: "Quand peut-on changer de méthode comptable ?", a: "Le principe de permanence des méthodes interdit les changements sauf si ceux-ci sont justifiés : nouvelle réglementation, modification de situation, meilleure image fidèle. Le changement doit être justifié et mentionné en annexe avec son impact." },
    { id: 'ue10-149', ue: 10, q: "Quels sont les événements postérieurs à la clôture ?", a: "Faits survenus entre la clôture et l'arrêté des comptes : ceux qui confirment des situations existantes à la clôture (litige, faillite d'un client) donnent lieu à ajustement des comptes ; ceux qui concernent des situations nouvelles sont mentionnés dans l'annexe." },

    // ========== 5. Annexe et états financiers ==========
    { id: 'ue10-28', ue: 10, q: "Les trois documents des comptes annuels ?", a: "Bilan, compte de résultat et annexe. Depuis le règlement ANC 2022-06, deux modèles de bilan et de compte de résultat s'appliquent selon la taille ; plus de distinction base, abrégé et développé.", d: PCG25 },
    { id: 'ue10-150', ue: 10, q: "Que contient l'annexe des comptes annuels ?", a: "Règles et méthodes comptables, tableau des immobilisations et des amortissements, état des provisions et dépréciations, état des créances et dettes avec échéances, produits et charges à rattacher, engagements financiers (hors bilan), effectifs, rémunérations des dirigeants, événements postérieurs, tableaux normés." },
    { id: 'ue10-151', ue: 10, q: "Qu'est-ce que le bilan et comment se présente-t-il ?", a: "Photographie du patrimoine à la clôture : actif (immobilisations, actif circulant, régularisation, trésorerie) en valeurs brutes, amortissements et dépréciations, nettes ; passif (capitaux propres, provisions, dettes). Équation : actif = capitaux propres + provisions + dettes." },
    { id: 'ue10-152', ue: 10, q: "Compte de résultat par nature : structure ?", a: "Produits d'exploitation (ventes, production stockée/immobilisée, subventions...) − charges d'exploitation = résultat d'exploitation ; résultat financier ; résultat exceptionnel (restreint depuis 2025) ; impôts sur les bénéfices ; résultat net.", d: PCG25 },
    { id: 'ue10-29', ue: 10, q: "Soldes intermédiaires de gestion : de la marge commerciale à l'EBE ?", a: "Marge commerciale = ventes de marchandises − coût d'achat des marchandises vendues. Valeur ajoutée = marge commerciale + production de l'exercice − consommations en provenance de tiers. EBE = VA + subventions d'exploitation − impôts et taxes − charges de personnel." },

    // ========== 6. Secteur non lucratif ==========
    { id: 'ue10-153', ue: 10, q: "Quelles entités relèvent de la comptabilité des organismes à but non lucratif ?", a: "Associations, fondations, fonds de dotation, syndicats, partis politiques... Elles appliquent le règlement ANC n° 2018-06 relatif aux comptes annuels des personnes morales de droit privé à but non lucratif, adapté au PCG.", d: "ANC 2018-06 (exercices ouverts depuis le 01/01/2020) — à confirmer avec ton cours" },
    { id: 'ue10-154', ue: 10, q: "Quelles sont les ressources d'une association ?", a: "Cotisations, dons manuels, legs et donations, subventions (de fonctionnement et d'investissement), produits d'activités (ventes, prestations), parrainage et mécénat, produits financiers. Leur comptabilisation dépend de la date de décision, de l'affectation et des conditions." },
    { id: 'ue10-155', ue: 10, q: "Quelle est la structure des fonds propres d'une association ?", a: "Fonds propres : fonds associatifs sans droit de reprise (apports sans reprise, réserves, résultat) et avec droit de reprise (apports avec droit de reprise), report à nouveau, résultat, subventions d'investissement, provisions réglementées. Les fonds associatifs remplacent le capital." },
    { id: 'ue10-156', ue: 10, q: "Fonds dédiés : de quoi s'agit-il ?", a: "Ressources affectées par un tiers à un projet précis mais non encore utilisées à la clôture : la fraction non consommée est inscrite en « fonds dédiés » au passif (classe 19), par une charge « engagements à réaliser sur ressources affectées » (689), et reprise à mesure de l'utilisation (« report des ressources non utilisées », 789).", d: "ANC 2018-06 — à confirmer avec ton cours" },
    { id: 'ue10-157', ue: 10, q: "Compte de résultat par origine et destination (CROD) ?", a: "Présentation complémentaire qui ventile les emplois par destination (missions sociales, frais de recherche de fonds, frais de fonctionnement et autres) et les ressources par origine (générosité du public, subventions, autres). Obligatoire pour les organismes faisant appel public à la générosité." },
    { id: 'ue10-158', ue: 10, q: "Contributions volontaires en nature et bénévolat ?", a: "Bénévolat, mises à disposition gratuites de biens ou de personnel, dons en nature : valorisés dans un tableau de contributions volontaires en nature (hors bilan, en pied de compte de résultat ou annexe) selon des règles d'évaluation justifiées." },
    { id: 'ue10-159', ue: 10, q: "Comment comptabiliser une subvention reçue par une association ?", a: "Subvention d'exploitation : produit de l'exercice dès que le droit est acquis (décision d'attribution), avec fonds dédiés si affectée à un projet non réalisé. Subvention d'investissement : en capitaux propres puis reprise au résultat au rythme de l'amortissement du bien subventionné.", d: "ANC 2018-06 — à confirmer avec ton cours" },

    // ========== Consolidation (statut à vérifier avec le programme 2027) ==========
    { id: 'ue10-30', ue: 10, q: "Consolidation : critères de contrôle et méthode associée ?", a: "Contrôle exclusif (plus de 50 % des droits de vote, ou présomption à plus de 40 % si aucun autre associé ne détient davantage) → intégration globale. Contrôle conjoint → intégration proportionnelle. Influence notable (présumée à partir de 20 % des droits de vote) → mise en équivalence.", d: "Règlement ANC 2020-01 ; la place de la consolidation dans le nouveau programme (DSCG) est à vérifier" },
    { id: 'ue10-31', ue: 10, q: "Étapes de la consolidation par intégration globale ?", a: "Retraitements d'homogénéisation, cumul des comptes, élimination des opérations intragroupe, élimination des titres contre la quote-part de capitaux propres (écart d'acquisition), partage des capitaux propres entre groupe et intérêts minoritaires.", d: "À vérifier : consolidation possiblement hors programme du DCG 2027" },
    { id: 'ue10-32', ue: 10, q: "Écart d'acquisition et intérêts minoritaires ?", a: "Écart d'acquisition = prix d'acquisition des titres − quote-part dans la juste valeur de l'actif net identifiable (goodwill, positif ou négatif). Intérêts minoritaires = quote-part des capitaux propres et du résultat de la filiale détenue par les tiers.", d: "À vérifier : consolidation possiblement hors programme du DCG 2027" }
  );

  Q.push(
    { id: 'q-ue10-01', ue: 10, q: "Un bien acheté 20 000 € et amorti de 12 000 € est cédé 9 500 €. Résultat de cession ?", choices: ["Plus-value de 1 500 €", "Moins-value de 1 500 €", "Plus-value de 9 500 €", "Moins-value de 8 000 €"], answer: 0, expl: "VNC = 20 000 − 12 000 = 8 000 €. 9 500 − 8 000 = +1 500 € (plus-value)." },
    { id: 'q-ue10-02', ue: 10, q: "Quel principe impose de provisionner un risque probable ?", choices: ["Continuité d'exploitation", "Prudence", "Permanence des méthodes", "Coût historique"], answer: 1, expl: "Principe de prudence : on tient compte des risques et pertes probables, pas des gains latents." },
    { id: 'q-ue10-03', ue: 10, q: "Une charge constatée d'avance correspond à une charge…", choices: ["Payée sur l'exercice et relative à l'exercice suivant", "À payer relative à l'exercice", "Exceptionnelle", "Non déductible"], answer: 0, expl: "On la retire des charges de l'exercice N (compte 486) car elle concerne N+1." },
    { id: 'q-ue10-04', ue: 10, q: "Machine de 30 000 € mise en service le 1er avril, amortie 5 ans en linéaire. Annuité de la 1re année ?", choices: ["6 000 €", "4 500 €", "5 000 €", "3 000 €"], answer: 1, expl: "30 000 ÷ 5 = 6 000 € par an ; prorata 9/12 → 4 500 €." },
    { id: 'q-ue10-05', ue: 10, q: "Bien de 24 000 €, 5 ans, dégressif, acquis le 1er janvier. Première annuité ?", choices: ["4 800 €", "6 000 €", "8 400 €", "10 800 €"], answer: 2, expl: "Taux linéaire 20 % × 1,75 = 35 % ; 24 000 × 35 % = 8 400 €." },
    { id: 'q-ue10-06', ue: 10, q: "Créance client douteuse de 1 200 € TTC (TVA 20 %), perte probable estimée à 50 %. Dépréciation ?", choices: ["600 €", "500 €", "1 000 €", "1 200 €"], answer: 1, expl: "La dépréciation se calcule sur le HT : 1 000 × 50 % = 500 €." },
    { id: 'q-ue10-07', ue: 10, q: "Assurance annuelle de 1 200 € payée le 1er octobre N. Charge constatée d'avance au 31/12/N ?", choices: ["300 €", "600 €", "900 €", "1 200 €"], answer: 2, expl: "9 mois sur 12 concernent N+1 : 1 200 × 9/12 = 900 €." },
    { id: 'q-ue10-08', ue: 10, q: "Stock de marchandises : SI 10 000, SF 12 500. Quelle écriture de variation de stocks ?", choices: ["Débit 6037 de 2 500 €", "Crédit 6037 de 2 500 €", "Crédit 6037 de 12 500 €", "Débit 37 de 10 000 €"], answer: 1, expl: "Le stock augmente de 2 500 € : on crédite 6037 (diminution de charges)." },
    { id: 'q-ue10-09', ue: 10, q: "Machine achetée 50 000 €, amortie 32 000 €, cédée 15 000 €. Résultat de cession ?", choices: ["Moins-value de 3 000 €", "Plus-value de 3 000 €", "Moins-value de 18 000 €", "Plus-value de 15 000 €"], answer: 0, expl: "VNC = 18 000 € ; 15 000 − 18 000 = −3 000 € (moins-value)." },
    { id: 'q-ue10-10', ue: 10, q: "Une société détient 55 % des droits de vote d'une autre. Méthode de consolidation ?", choices: ["Mise en équivalence", "Intégration proportionnelle", "Intégration globale", "Aucune"], answer: 2, expl: "Contrôle exclusif (plus de 50 % des droits de vote) → intégration globale.", d: "Consolidation : à vérifier dans le programme 2027" },
    { id: 'q-ue10-11', ue: 10, q: "Une participation de 25 % avec influence notable est consolidée par…", choices: ["Intégration globale", "Intégration proportionnelle", "Mise en équivalence", "Cumul simple"], answer: 2, expl: "Influence notable (présumée dès 20 % des droits de vote) → mise en équivalence.", d: "Consolidation : à vérifier dans le programme 2027" },
    { id: 'q-ue10-12', ue: 10, q: "Les amortissements dérogatoires (compte 145) figurent…", choices: ["À l'actif", "Dans les capitaux propres (provisions réglementées)", "Dans les dettes fournisseurs", "Dans les charges à payer"], answer: 1, expl: "Ce sont des provisions réglementées, rattachées aux capitaux propres." },
    { id: 'q-ue10-101', ue: 10, q: "Avec le PCG 2025, dans quel compte enregistre-t-on la valeur comptable d'une immobilisation courante cédée ?", choices: ["675", "657", "6811", "654"], answer: 1, expl: "Depuis les exercices ouverts à compter du 01/01/2025, le compte 657 remplace le compte 675 (la cession courante n'est plus en résultat exceptionnel).", d: PCG25 },
    { id: 'q-ue10-102', ue: 10, q: "Avec le PCG 2025, dans quel compte enregistre-t-on le prix de cession d'une immobilisation courante ?", choices: ["775", "757", "707", "7584"], answer: 1, expl: "Le compte 757 remplace le compte 775.", d: PCG25 },
    { id: 'q-ue10-103', ue: 10, q: "Avec le PCG 2025, la quote-part de subvention d'investissement virée au résultat est créditée au compte…", choices: ["777", "747", "7584", "139"], answer: 1, expl: "Débit 139 / crédit 747 (ancien compte 777), dans le résultat d'exploitation.", d: PCG25 },
    { id: 'q-ue10-104', ue: 10, q: "Que supprime le PCG 2025 ?", choices: ["Les amortissements", "Les transferts de charges (comptes 791, 796, 797)", "Le principe de prudence", "L'annexe"], answer: 1, expl: "La technique du transfert de charges est supprimée ; on comptabilise selon la nature (708, 649, 7587, 741...).", d: PCG25 },
    { id: 'q-ue10-105', ue: 10, q: "Marché de 100 000 €, coûts totaux estimés 80 000 €, coûts engagés à ce jour 40 000 €. CA reconnu à l'avancement ?", choices: ["40 000 €", "50 000 €", "80 000 €", "100 000 €"], answer: 1, expl: "Taux d'avancement = 40 000 ÷ 80 000 = 50 % ; CA = 100 000 × 50 % = 50 000 €." },
    { id: 'q-ue10-106', ue: 10, q: "Emprunt de 100 000 € à 6 % : intérêts courus pour 3 mois à la clôture ?", choices: ["500 €", "1 500 €", "3 000 €", "6 000 €"], answer: 1, expl: "100 000 × 6 % × 3/12 = 1 500 € (débit 661 / crédit 1688)." },
    { id: 'q-ue10-107', ue: 10, q: "Émission de 1 000 actions de nominal 10 € à 15 € : quel montant de prime d'émission ?", choices: ["5 000 €", "10 000 €", "15 000 €", "0 €"], answer: 0, expl: "Capital : 1 000 × 10 = 10 000 € ; apport total : 15 000 € ; prime d'émission (1041) = 5 000 €." },
    { id: 'q-ue10-108', ue: 10, q: "Résultat fiscal de 100 000 €, PME éligible au taux réduit, acomptes versés 12 000 €. IS à payer (solde) ?", choices: ["8 750 €", "20 750 €", "13 000 €", "25 000 €"], answer: 0, expl: "IS = 42 500 × 15 % + 57 500 × 25 % = 20 750 € ; solde = 20 750 − 12 000 = 8 750 €.", d: "Taux d'IS 2026" },
    { id: 'q-ue10-109', ue: 10, q: "Un changement d'estimation de la durée d'utilisation d'une immobilisation est traité…", choices: ["Rétroactivement, avec impact en report à nouveau", "Prospectivement, avec impact en résultat", "Par une provision", "Il est interdit"], answer: 1, expl: "Le changement d'estimation est prospectif : la VNC est amortie sur la durée révisée." },
    { id: 'q-ue10-110', ue: 10, q: "Un changement de méthode comptable est traité…", choices: ["Rétrospectivement, avec impact en report à nouveau", "Prospectivement, avec impact en résultat", "Sans trace en annexe", "En produit exceptionnel"], answer: 0, expl: "Le changement de méthode est rétrospectif avec impact en réserves (report à nouveau) et mention en annexe." },
    { id: 'q-ue10-111', ue: 10, q: "Stocks : 100 unités à 10 € puis 300 unités à 12 €. Valeur d'une sortie de 200 unités en CMUP de fin de période ?", choices: ["2 000 €", "2 300 €", "2 400 €", "2 100 €"], answer: 1, expl: "CMUP = (1 000 + 3 600) ÷ 400 = 11,50 € ; 200 × 11,50 = 2 300 €." },
    { id: 'q-ue10-112', ue: 10, q: "Les provisions pour risques et charges sont comptabilisées en classe…", choices: ["Classe 1", "Classe 2", "Classe 4", "Classe 7"], answer: 0, expl: "Les provisions pour risques et charges (compte 15) figurent en classe 1 ; leur dotation (6815) en classe 6." },
    { id: 'q-ue10-113', ue: 10, q: "Les « fonds dédiés » d'une association représentent…", choices: ["Des dons reçus sans affectation", "Des ressources affectées par un tiers à un projet et non encore utilisées à la clôture", "Un emprunt", "Des réserves statutaires"], answer: 1, expl: "Fonds dédiés : fraction des ressources affectées non consommée à la clôture, portée au passif.", d: "ANC 2018-06 — à confirmer avec ton cours" },
    { id: 'q-ue10-114', ue: 10, q: "Quelle est la méthode de reconnaissance du résultat d'un contrat à long terme qui reconnaît le résultat à la livraison ?", choices: ["À l'avancement", "À l'achèvement", "Au prorata du temps", "À la facturation"], answer: 1, expl: "À l'achèvement, le résultat n'est constaté qu'à la livraison ; à l'avancement, il est reconnu au fil de l'exécution." },
    { id: 'q-ue10-115', ue: 10, q: "L'amortissement d'un composant (ex. toiture) se justifie car…", choices: ["Sa durée d'utilisation est différente de celle de l'immeuble", "Il est plus cher", "Il est obligatoire pour tous les biens", "Il n'est jamais remplacé"], answer: 0, expl: "Approche par composants : on amortit séparément les éléments dont la durée d'utilisation est différente." },
    { id: 'q-ue10-116', ue: 10, q: "Une facture d'électricité de décembre N, reçue en janvier N+1, est enregistrée en N par…", choices: ["Une charge constatée d'avance", "Une facture non parvenue (charge à payer)", "Un produit à recevoir", "Une provision pour litige"], answer: 1, expl: "C'est une charge de N non encore facturée : facture non parvenue (compte 408)." },
    { id: 'q-ue10-117', ue: 10, q: "Les frais de développement peuvent être immobilisés si…", choices: ["Jamais", "Le projet est distinct, techniquement faisable et rentable", "Ils sont inférieurs à 100 000 €", "Ils ont été payés par un client"], answer: 1, expl: "Les frais de développement sont immobilisables sous conditions (projet distinct, faisabilité, rentabilité, volonté d'achever) ; les frais de recherche sont des charges." },
    { id: 'q-ue10-118', ue: 10, q: "Quelle définition retient le PCG 2025 pour le résultat exceptionnel ?", choices: ["Tous les produits et charges rares", "Les produits et charges liés à un événement majeur, inhabituel et rare", "Les cessions d'immobilisations", "Les dotations aux provisions"], answer: 1, expl: "La définition est restrictive : événement majeur et inhabituel ; les cessions courantes en sortent.", d: PCG25 }
  );
})();
