/* UE 11 — compléments : calculs, cartes à trous, méthode, lexique. Ajouter uniquement à la fin. */

// ===== Calculs (tous vérifiés numériquement) =====
DCG_FLASH(11, [
  ["CA 200 000 €, charges variables 120 000 € : MCV et taux de MCV ?", "MCV = 200 000 − 120 000 = 80 000 € ; taux = 80 000 ÷ 200 000 = 40 %.", "ue11-01", null, "calc"],
  ["Charges fixes 60 000 €, taux de MCV 40 % : seuil de rentabilité ?", "SR = 60 000 ÷ 0,40 = 150 000 €.", "ue11-02", null, "calc"],
  ["CA 200 000 €, SR 150 000 € : marge de sécurité et indice de sécurité ?", "Marge de sécurité = 50 000 € ; indice = 50 000 ÷ 200 000 = 25 %.", "ue11-03", null, "calc"],
  ["MCV 80 000 €, charges fixes 60 000 € : résultat ?", "80 000 − 60 000 = 20 000 €.", "ue11-01", null, "calc"],
  ["MCV 80 000 €, résultat 20 000 € : levier opérationnel ? Effet d'une hausse de CA de 5 % ?", "Levier = 80 000 ÷ 20 000 = 4 ; le résultat augmente de 5 % × 4 = 20 % (soit 24 000 €).", "ue11-14", null, "calc"],
  ["SR 150 000 €, CA annuel 200 000 € réparti uniformément : point mort ?", "150 000 ÷ 200 000 × 12 = 9 mois : atteint fin septembre (30 septembre).", "ue11-15", null, "calc"],
  ["Prix 50 €, coût variable unitaire 30 €, charges fixes 60 000 € : SR en quantité ?", "Marge unitaire = 20 € ; SR = 60 000 ÷ 20 = 3 000 unités.", "ue11-02", null, "calc"],
  ["Même produit : quantité à vendre pour un résultat de 25 000 € ?", "(60 000 + 25 000) ÷ 20 = 4 250 unités.", "ue11-02", null, "calc"],
  ["Même produit : si les charges fixes augmentent de 10 000 €, nouveau SR en quantité ?", "70 000 ÷ 20 = 3 500 unités.", "ue11-02", null, "calc"],
  ["Charges fixes 90 000 €, taux de MCV 30 % : SR ?", "90 000 ÷ 0,30 = 300 000 €.", "ue11-02", null, "calc"],
  ["Prix 100 € → 110 €, coût variable 60 € : taux de MCV avant et après ?", "Avant : 40 ÷ 100 = 40 %. Après : 50 ÷ 110 ≈ 45,45 %.", "ue11-01", null, "calc"],
  ["A : CA 300 000 €, CV 180 000 € ; B : CA 200 000 €, CV 100 000 € ; charges fixes 140 000 € : SR global ?", "MCV totale = 120 000 + 100 000 = 220 000 € ; taux = 220 ÷ 500 = 44 % ; SR = 140 000 ÷ 0,44 ≈ 318 182 €.", "ue11-117", null, "calc"],
  ["Même cas : SR du produit A (structure du CA constante) ?", "A représente 60 % du CA : 318 182 × 0,60 ≈ 190 909 € (B : 127 273 €).", "ue11-117", null, "calc"],
  ["Charges fixes réelles 120 000 €, activité normale 1 000 h, activité réelle 800 h : imputation rationnelle ?", "Coefficient = 0,8 ; charges fixes imputées = 96 000 € ; coût de sous-activité = 24 000 €.", "ue11-12", null, "calc"],
  ["Mêmes charges fixes, activité réelle 1 200 h : imputation rationnelle ?", "Coefficient = 1,2 ; charges fixes imputées = 144 000 € ; boni de suractivité = 24 000 €.", "ue11-12", null, "calc"],
  ["Production 1 000 u, ventes 800 u, charges fixes 20 000 € : écart de résultat entre coût complet et direct costing ?", "200 u en stock × 20 € de charges fixes unitaires = 4 000 € de charges fixes stockées : le coût complet donne un résultat supérieur de 4 000 €.", "ue11-13", null, "calc"],
  ["Stock initial 100 u à 10 € ; entrée 300 u à 12 € ; sortie 250 u : CMUP et stock final ?", "CMUP = (1 000 + 3 600) ÷ 400 = 11,50 € ; sortie = 2 875 € ; stock final = 150 × 11,50 = 1 725 €.", "ue11-11", null, "calc"],
  ["Mêmes données en FIFO : valeur de la sortie et du stock final ?", "Sortie = 100 × 10 + 150 × 12 = 2 800 € ; stock final = 150 × 12 = 1 800 €.", "ue11-11", null, "calc"],
  ["Achat de matières 10 000 € + frais d'achat 800 € : coût d'achat ?", "10 800 €.", "ue11-10", null, "calc"],
  ["Matières consommées 10 800 €, MOD 6 000 €, charges indirectes de production 3 200 €, 500 unités : coût de production unitaire ?", "Coût de production = 20 000 € ; unitaire = 20 000 ÷ 500 = 40 €.", "ue11-05", null, "calc"],
  ["Coût de production des produits vendus 20 000 €, distribution 2 500 €, CA 27 000 € : coût de revient et résultat analytique ?", "Coût de revient = 22 500 € ; résultat = 27 000 − 22 500 = 4 500 €.", "ue11-10", null, "calc"],
  ["Section : 24 000 € de charges, 1 200 h-machine : coût de l'unité d'œuvre ?", "24 000 ÷ 1 200 = 20 € par heure-machine.", "ue11-113", null, "calc"],
  ["Frais de distribution 8 000 €, CA 80 000 € : taux de frais exprimé en % du CA ?", "8 000 ÷ 80 000 = 10 % du CA.", "ue11-113", null, "calc"],
  ["A = 10 000 + 20 % de B ; B = 6 000 + 10 % de A : totaux des sections ?", "A = 11 200 ÷ 0,98 ≈ 11 428,57 € ; B = 6 000 + 1 142,86 ≈ 7 142,86 €.", "ue11-114", null, "calc"],
  ["800 produits finis + 200 en-cours à 50 % d'avancement, coûts 18 000 € : coût unitaire ?", "Unités équivalentes = 800 + 100 = 900 ; coût = 18 000 ÷ 900 = 20 €.", "ue11-115", null, "calc"],
  ["Coût commun 60 000 € ; P1 : 1 000 u à 50 € ; P2 : 500 u à 40 € : répartition par valeur de vente ?", "CA total 70 000 € ; P1 = 60 000 × 50/70 ≈ 42 857 € ; P2 ≈ 17 143 €.", "ue11-116", null, "calc"],
  ["Matières : Ps 5 €, Pr 5,40 €, Qs 1 000 kg, Qr 1 100 kg : écarts sur prix, quantité et global ?", "Prix = 0,40 × 1 100 = 440 € D ; quantité = 100 × 5 = 500 € D ; global = 5 940 − 5 000 = 940 € D.", "ue11-21", null, "calc"],
  ["MOD : Ts 12 €, Tr 12,50 €, Hs 400 h, Hr 380 h : écarts sur taux, temps et global ?", "Taux = 0,50 × 380 = 190 € D ; temps = (380 − 400) × 12 = 240 € F ; global = 4 750 − 4 800 = 50 € F.", "ue11-22", null, "calc"],
  ["CA prévu : 1 000 u à 20 € ; réel : 1 100 u à 19 € : écarts sur prix, quantité, global ?", "Prix = (19 − 20) × 1 100 = 1 100 € D ; quantité = 100 × 20 = 2 000 € F ; global = 20 900 − 20 000 = 900 € F.", "ue11-24", null, "calc"],
  ["Marge unitaire prévue 8 €, réelle 7 € ; ventes prévues 1 000 u, réelles 1 100 u : écarts sur volume, sur marge unitaire, global ?", "Volume = 100 × 8 = 800 € F ; marge unitaire = (7 − 8) × 1 100 = 1 100 € D ; global = 7 700 − 8 000 = 300 € D.", "ue11-24", null, "calc"],
  ["Coût réel des charges indirectes 51 000 €, budget flexible de l'activité réelle 50 000 € : écart sur budget ?", "51 000 − 50 000 = 1 000 € (défavorable).", "ue11-23", null, "calc"],
  ["Charges fixes 50 000 €, charges variables 8 €/u : budget flexible pour 6 000 u ?", "50 000 + 8 × 6 000 = 98 000 €.", "ue11-128", null, "calc"],
  ["Résultat 90 000 €, capitaux investis 600 000 € : ROI ? Résultat résiduel au taux de 12 % ?", "ROI = 15 % ; résultat résiduel = 90 000 − 0,12 × 600 000 = 18 000 €.", "ue11-29", null, "calc"],
  ["Marge de 10 % et rotation du capital de 1,5 : ROI ?", "ROI = marge × rotation = 10 % × 1,5 = 15 %.", "ue11-29", null, "calc"],
  ["NOPAT 150 000 €, capital investi 1 500 000 €, coût du capital 8 % : EVA ?", "150 000 − 0,08 × 1 500 000 = 30 000 € : valeur créée.", "ue11-110", null, "calc"],
  ["Coût complet unitaire de cession 50 € + marge de 10 % : prix de cession interne ?", "50 × 1,10 = 55 €.", "ue11-28", null, "calc"],
  ["Produire 5 000 u : 18 €/u variable + 30 000 € de charges fixes évitables ; sous-traitant à 22 € l'unité : décision ?", "Interne : 5 000 × 18 + 30 000 = 120 000 € ; achat : 110 000 € → faire faire (économie de 10 000 €).", "ue11-119", null, "calc"],
  ["Commande spéciale 2 000 u à 25 €, coût variable 18 €, capacité disponible, charges fixes inchangées : accepter ?", "MCV = 7 × 2 000 = 14 000 € > 0 : on accepte (le coût complet ne doit pas guider cette décision).", "ue11-118", null, "calc"],
  ["Produit : MCV 40 000 €, charges fixes spécifiques 25 000 € : l'abandonner ?", "Marge sur coût spécifique = 15 000 € > 0 : on le conserve (sauf meilleure utilisation de la capacité).", "ue11-30", null, "calc"],
  ["ABC : 30 000 € de coûts de lancement, 150 lancements ; produit X : 40 lancements. Coût imputé à X ?", "Inducteur = 200 €/lancement ; X = 40 × 200 = 8 000 €.", "ue11-16", null, "calc"],
  ["Prix de marché 120 €, marge souhaitée 25 % du prix : coût cible ?", "Marge = 30 € ; coût cible = 120 − 30 = 90 €.", "ue11-17", null, "calc"],
  ["Ventes mars 60 000 € TTC, avril 80 000 € TTC ; 30 % comptant, 70 % à 30 jours : encaissements d'avril ?", "0,30 × 80 000 + 0,70 × 60 000 = 24 000 + 42 000 = 66 000 €.", "ue11-19", null, "calc"],
  ["Ventes HT 50 000 €, achats HT 20 000 €, TVA 20 % : TVA à décaisser ?", "Collectée 10 000 − déductible 4 000 = 6 000 €.", "ue11-19", null, "calc"],
  ["Ventes trimestrielles 10, 12, 14, 16 (périodes 1 à 4) : droite d'ajustement et prévision de la période 5 ?", "y = 2x + 8 (pente 2, ordonnée 8) ; période 5 : 2 × 5 + 8 = 18.", "ue11-126", null, "calc"],
  ["Valeur observée 120, tendance 100 : coefficient saisonnier ? Prévision avec tendance 110 ?", "Coefficient = 120 ÷ 100 = 1,2 ; prévision = 110 × 1,2 = 132.", "ue11-126", null, "calc"]
]);

// ===== Cartes à trous =====
DCG_CLOZE(11, [
  ["La marge sur coût variable = chiffre d'affaires − {{charges variables}}.", "ue11-01"],
  ["Le seuil de rentabilité = {{charges fixes}} ÷ taux de marge sur coût variable.", "ue11-02"],
  ["La marge de sécurité = chiffre d'affaires − {{seuil de rentabilité}}.", "ue11-03"],
  ["Le levier opérationnel = marge sur coût variable ÷ {{résultat d'exploitation}}.", "ue11-14"],
  ["Le point mort est la {{date}} à laquelle le seuil de rentabilité est atteint.", "ue11-15"],
  ["Une charge {{incorporable}} est une charge de la comptabilité générale retenue dans le calcul des coûts.", "ue11-04"],
  ["Une charge {{supplétive}} n'est pas enregistrée en comptabilité générale mais est retenue en comptabilité de gestion (ex. rémunération de l'exploitant).", "ue11-04"],
  ["Une charge {{non incorporable}} est enregistrée en comptabilité générale mais exclue des coûts (ex. charges exceptionnelles).", "ue11-04"],
  ["Une charge {{directe}} est affectable directement à un coût sans calcul préalable.", "ue11-08"],
  ["Une charge {{indirecte}} est commune à plusieurs coûts et doit être répartie.", "ue11-08"],
  ["Le coût d'achat = prix d'achat + {{frais d'achat}}.", "ue11-10"],
  ["Le coût de revient = coût de production des produits vendus + {{charges de distribution}} (et autres charges hors production).", "ue11-10"],
  ["Dans la méthode des centres d'analyse, on répartit d'abord les charges {{primaires}} puis on opère la répartition {{secondaire}} des sections auxiliaires.", "ue11-09"],
  ["Les {{prestations réciproques}} entre sections auxiliaires se résolvent par un système d'équations.", "ue11-114"],
  ["L'{{unité d'œuvre}} est la mesure de l'activité d'une section (heure-machine, kg de matière...).", "ue11-113"],
  ["Le CMUP est le coût moyen {{unitaire pondéré}} ; en FIFO les sorties sont valorisées au coût des {{plus anciennes}} entrées.", "ue11-11"],
  ["Le coefficient d'imputation rationnelle = activité {{réelle}} ÷ activité {{normale}}.", "ue11-12"],
  ["Le coût de {{sous-activité}} correspond aux charges fixes non imputées quand l'activité réelle est inférieure à l'activité normale.", "ue11-12"],
  ["Le direct costing {{simple}} ne retient que les charges variables ; le {{évolué}} distingue en plus les charges fixes spécifiques.", "ue11-13"],
  ["Dans l'ABC, les charges indirectes sont regroupées par {{activités}} et affectées via des {{inducteurs de coûts}}.", "ue11-16"],
  ["Le target costing part du {{prix de vente}} accepté par le marché pour en déduire le coût cible.", "ue11-17"],
  ["Coût cible = prix de vente − {{marge souhaitée}}.", "ue11-17"],
  ["Le TDABC (Kaplan et Anderson) utilise le {{temps}} comme inducteur principal.", "ue11-121"],
  ["Le budget des ventes est le premier de la chaîne budgétaire car les ventes constituent en général le {{facteur limitant}}.", "ue11-18"],
  ["Le budget de {{trésorerie}} reprend les encaissements et décaissements prévus et fait apparaître le solde de trésorerie.", "ue11-19"],
  ["Un budget {{flexible}} s'ajuste au niveau d'activité réellement atteint.", "ue11-128"],
  ["Le budget {{glissant}} est actualisé périodiquement sur un horizon constant ; le budget {{base zéro}} remet en cause toutes les dépenses.", "ue11-129"],
  ["Dans une démarche {{top-down}}, la direction fixe les objectifs ; dans une démarche {{bottom-up}}, ils remontent du terrain.", "ue11-130"],
  ["L'écart sur prix des matières = (Pr − Ps) × {{Qr}}.", "ue11-21"],
  ["L'écart sur quantité des matières = (Qr − Qs) × {{Ps}}.", "ue11-21"],
  ["L'écart sur taux de la main-d'œuvre = (Tr − Ts) × {{Hr}}.", "ue11-22"],
  ["L'écart sur temps de la main-d'œuvre = (Hr − Hs) × {{Ts}}.", "ue11-22"],
  ["Un écart est {{défavorable}} lorsqu'il diminue le résultat (coût réel supérieur au standard ou produit inférieur au prévu).", "ue11-20"],
  ["L'écart sur budget des charges indirectes = coût réel − budget {{flexible}} de l'activité réelle.", "ue11-23"],
  ["Un coût {{standard}} est un coût préétabli par unité produite, base du calcul des écarts.", "ue11-132"],
  ["Un tableau de bord est un outil de pilotage à {{court}} terme, composé d'indicateurs peu nombreux et pertinents.", "ue11-25"],
  ["Les quatre axes du balanced scorecard : {{financier}}, {{clients}}, processus internes, apprentissage organisationnel.", "ue11-26"],
  ["Le {{ROI}} d'un centre d'investissement = résultat ÷ capitaux investis.", "ue11-29"],
  ["Le résultat {{résiduel}} = résultat − capitaux investis × taux de rendement exigé.", "ue11-29"],
  ["Un centre de {{profit}} est responsable de ses charges et de ses produits ; un centre de {{coûts}} des seules charges.", "ue11-27"],
  ["Le prix de cession interne peut être fixé au coût, au prix du {{marché}} ou être {{négocié}}.", "ue11-28"],
  ["Anthony distingue trois niveaux : planification {{stratégique}}, contrôle de {{gestion}}, contrôle {{opérationnel}}.", "ue11-07"],
  ["Pour ses {{leviers de contrôle}}, Simons distingue : systèmes de croyances, de limites, de contrôle diagnostique et de contrôle interactif.", "ue11-105"],
  ["L'{{EVA}} = NOPAT − coût du capital × capital investi.", "ue11-110"],
  ["Les coûts de qualité regroupent prévention, {{évaluation}} (contrôle), défaillances internes et {{défaillances externes}}.", "ue11-122"],
  ["Les {{coûts cachés}} (approche socio-économique, Savall) sont des dysfonctionnements non repérés par la comptabilité.", "ue11-123"]
]);

// ===== Méthode et lexique =====
DCG_FLASH(11, [
  ["Méthode : étapes pour un tableau de répartition des charges indirectes ?", "1) Charges par nature à répartir. 2) Répartition primaire entre sections (clés). 3) Répartition secondaire des auxiliaires (prestations réciproques éventuelles). 4) Total des sections principales. 5) Nature de l'unité d'œuvre. 6) Nombre d'unités d'œuvre. 7) Coût de l'unité d'œuvre.", "ue11-09", null, "ecr"],
  ["Méthode : enchaînement du calcul des coûts (coût complet) ?", "Coût d'achat → stock de matières (CMUP/FIFO) → coût de production → stock de produits finis → coût de revient → résultat analytique.", "ue11-10", null, "ecr"],
  ["Méthode : cas de seuil de rentabilité, par quoi commencer ?", "1) Distinguer charges variables et fixes (tableau d'exploitation différentiel). 2) Calculer MCV et taux. 3) SR = CF ÷ taux. 4) Marge/indice de sécurité, point mort, levier.", "ue11-02", null, "ecr"],
  ["Méthode : calcul des écarts, ordre à suivre ?", "1) Écart global (réel − standard). 2) Standard pour la production réelle (Qs, Hs). 3) Décomposer en prix/taux et quantité/temps. 4) Vérifier que la somme = global. 5) Sens (F/D) et causes.", "ue11-20", null, "ecr"],
  ["Méthode : établir un budget de trésorerie ?", "Partir des budgets (ventes, achats, personnel, investissements) ; tenir compte des délais de règlement ET de la TVA (TTC) ; encaissements − décaissements = flux du mois ; trésorerie initiale + flux = trésorerie finale.", "ue11-19", null, "ecr"],
  ["Méthode : décision de gestion (commande spéciale, abandon, make or buy) ?", "Raisonner en coûts et marges différentiels : seuls comptent les flux évitables ou supplémentaires. On ignore les charges fixes inchangées. On conclut puis on cite les limites qualitatives (capacité, image, risques).", "ue11-118", null, "ecr"],
  ["Méthode : rédiger une réponse commentée sur un indicateur ?", "Définir l'indicateur, donner la valeur, comparer (prévu, N−1, concurrents), interpréter le sens, proposer une action. Une réponse chiffrée sans commentaire perd des points.", "ue11-133", null, "ecr"],
  ["Méthode : coût complet ou coût partiel, comment choisir ?", "Coût complet : fixer les prix, valoriser les stocks, calculer la rentabilité à long terme. Coûts partiels : décisions à court terme, seuil de rentabilité, choix de gamme.", "ue11-13"],
  ["Qu'est-ce que la comptabilité de gestion ?", "Système d'information interne, non normalisé, qui calcule les coûts, marges et résultats pour aider les décisions de gestion. Elle complète la comptabilité générale (obligatoire et normalisée).", "ue11-06"],
  ["Qu'est-ce qu'un coût complet ?", "Coût qui intègre toutes les charges (directes et indirectes, variables et fixes) liées à un produit ou une activité.", "ue11-111"],
  ["Qu'est-ce qu'un coût marginal ?", "Variation du coût total résultant de la production d'une unité supplémentaire. Proche du coût variable à court terme.", "ue11-111"],
  ["Qu'est-ce qu'un coût évitable (ou différentiel) ?", "Coût qui disparaîtrait si une décision était prise (abandon, sous-traitance). Seuls les coûts évitables sont pertinents pour décider.", "ue11-118"],
  ["Qu'est-ce qu'un coût d'opportunité ?", "Gain auquel on renonce en choisissant une option plutôt qu'une autre. À intégrer dans les décisions à capacité limitée.", "ue11-118"],
  ["Qu'est-ce qu'un coût caché ?", "Coût de dysfonctionnements (absentéisme, rotation, non-qualité) non repérés par la comptabilité classique (approche socio-économique de Savall).", "ue11-123"],
  ["Qu'est-ce qu'un inducteur de coûts ?", "Facteur qui explique la consommation de ressources par une activité (ex. nombre de commandes, de lancements, d'heures de réglage).", "ue11-16"],
  ["Qu'est-ce qu'une activité (ABC) ?", "Ensemble de tâches homogènes consommant des ressources et produisant un résultat pour un produit, un client ou un service.", "ue11-16"],
  ["Qu'est-ce qu'un centre de responsabilité ?", "Unité de l'organisation dirigée par un responsable évalué sur des objectifs précis (coûts, profit, investissement).", "ue11-27"],
  ["Qu'est-ce que la congruence des objectifs ?", "Convergence des objectifs des responsables locaux avec ceux de l'entreprise (utile pour fixer prix de cession et indicateurs).", "ue11-28"],
  ["Qu'est-ce que le contrôle budgétaire ?", "Comparaison périodique des réalisations aux prévisions budgétaires, calcul des écarts, analyse des causes et actions correctives.", "ue11-131"],
  ["Qu'est-ce qu'un écart favorable ?", "Écart qui augmente le résultat : coût réel inférieur au standard, ou produits réels supérieurs au prévu.", "ue11-20"],
  ["Qu'est-ce que le benchmarking ?", "Comparaison de ses pratiques et performances à celles des meilleurs (internes ou externes) pour identifier des axes d'amélioration.", "ue11-136"],
  ["Qu'est-ce qu'un indicateur de résultat et un indicateur de pilotage (de processus) ?", "Résultat : constate le résultat final (CA, marge). Pilotage : mesure un levier d'action en amont (délai, taux de défauts) pour agir avant que le résultat soit dégradé.", "ue11-133"],
  ["Qu'est-ce que la valeur ajoutée client ?", "Ce que le client est prêt à payer en plus des coûts de production ; elle guide la conception à coût cible et l'analyse de la valeur.", "ue11-17"],
  ["Qu'est-ce que le coût de possession et de passation (gestion des stocks) ?", "Possession : stockage, immobilisation financière, assurance. Passation : traitement des commandes. Le modèle de Wilson minimise leur somme.", "ue11-11"],
  ["Qu'est-ce que le contrôle interne par rapport au contrôle de gestion ?", "Le contrôle interne vise la fiabilité de l'information, la conformité et la maîtrise des risques ; le contrôle de gestion vise la performance et l'atteinte des objectifs.", "ue11-101"],
  ["Qu'est-ce que la comptabilité environnementale (de gestion) ?", "Identification et suivi des coûts liés à l'environnement (déchets, énergie, émissions) pour piloter la performance globale.", "ue11-124"],
  ["Qu'est-ce que la cartographie des risques et la prévention de la fraude dans le pilotage ?", "Identifier les risques, évaluer leur probabilité et gravité, mettre en place des contrôles. Le contrôleur de gestion y contribue sans se confondre avec l'audit.", "ue11-101"]
]);

// ===== QCM supplémentaires =====
window.DCG_QCM.push(
  { id: 'q-ue11-150', ue: 11, q: "CA 200 000 €, charges variables 120 000 €, charges fixes 60 000 €. Le seuil de rentabilité est de :", choices: ["100 000 €", "150 000 €", "180 000 €", "200 000 €"], answer: 1, expl: "Taux de MCV = 40 % ; SR = 60 000 ÷ 0,40 = 150 000 €." },
  { id: 'q-ue11-151', ue: 11, q: "Un levier opérationnel de 4 signifie qu'une hausse de CA de 5 % entraîne une variation du résultat de :", choices: ["+ 1,25 %", "+ 5 %", "+ 9 %", "+ 20 %"], answer: 3, expl: "La variation du résultat = levier × variation du CA = 4 × 5 % = 20 %." },
  { id: 'q-ue11-152', ue: 11, q: "Quantité réelle de matières 1 100 kg, standard 1 000 kg, prix standard 5 €, prix réel 5,40 €. L'écart sur quantité est de :", choices: ["440 € D", "500 € D", "500 € F", "540 € D"], answer: 1, expl: "(1 100 − 1 000) × 5 = 500 € défavorable." },
  { id: 'q-ue11-153', ue: 11, q: "Activité normale 1 000 h, réelle 800 h, charges fixes 120 000 €. Le coût de sous-activité est de :", choices: ["12 000 €", "20 000 €", "24 000 €", "96 000 €"], answer: 2, expl: "Imputées = 120 000 × 0,8 = 96 000 € ; sous-activité = 120 000 − 96 000 = 24 000 €." },
  { id: 'q-ue11-154', ue: 11, q: "Quelle décision éclaire le mieux un raisonnement en coûts partiels ?", choices: ["La valorisation du stock de fin d'exercice", "L'acceptation d'une commande spéciale avec capacité disponible", "Le calcul du coût de revient pour la comptabilité générale", "La détermination du résultat fiscal"], answer: 1, expl: "Les décisions à court terme (commande spéciale, abandon, make or buy) reposent sur les marges et coûts différentiels." },
  { id: 'q-ue11-155', ue: 11, q: "Ventes mars 60 000 € TTC, avril 80 000 € TTC ; 30 % comptant, 70 % à 30 jours. Encaissements d'avril :", choices: ["24 000 €", "42 000 €", "56 000 €", "66 000 €"], answer: 3, expl: "0,30 × 80 000 + 0,70 × 60 000 = 66 000 €." }
);
