/* UE 2 — compléments : cas chiffrés, cartes à trous, méthode juridique, lexique. Ajouter uniquement à la fin. */

// ===== Cas chiffrés (calculs vérifiés) =====
DCG_FLASH(2, [
  ["Cession d'un fonds de commerce à 250 000 € : droits d'enregistrement (barème 0 / 3 / 5 %) ?", "(200 000 − 23 000) × 3 % + 50 000 × 5 % = 5 310 + 2 500 = 7 810 €.", "ue2-144", "Barème en vigueur en 2026 (à confirmer avec ton cours)", "calc"],
  ["Cession d'un fonds de commerce à 150 000 € : droits d'enregistrement ?", "(150 000 − 23 000) × 3 % = 3 810 € (rien sur la 1re tranche jusqu'à 23 000 €).", "ue2-144", "Barème en vigueur en 2026 (à confirmer avec ton cours)", "calc"],
  ["Cession d'un fonds de commerce à 22 000 € : droits d'enregistrement ?", "0 € : le prix ne dépasse pas la tranche exonérée de 23 000 €.", "ue2-144", "Barème en vigueur en 2026 (à confirmer avec ton cours)", "calc"],
  ["Cession de 50 % des parts d'une SARL pour 100 000 € : droits d'enregistrement (3 % après abattement de 23 000 € proratisé) ?", "Abattement = 23 000 × 50 % = 11 500 € ; droits = (100 000 − 11 500) × 3 % = 2 655 €.", "ue2-144", "Barème en vigueur en 2026 (à confirmer avec ton cours)", "calc"],
  ["Cession d'actions d'une SA pour 500 000 € : droits d'enregistrement (0,1 %) ?", "500 000 × 0,1 % = 500 €.", "ue2-144", "Barème en vigueur en 2026 (à confirmer avec ton cours)", "calc"],
  ["Capital de 100 000 €, bénéfice 40 000 €, report à nouveau déficitaire 10 000 €, réserve légale existante 8 000 € : dotation à la réserve légale ?", "5 % × (40 000 − 10 000) = 1 500 € ; le plafond restant (10 000 − 8 000 = 2 000 €) n'est pas atteint → 1 500 €.", "ue2-21", null, "calc"],
  ["Capital de 100 000 €, réserve légale déjà de 9 800 €, bénéfice 30 000 € : dotation ?", "5 % × 30 000 = 1 500 € mais la réserve est plafonnée à 10 % du capital (10 000 €) : dotation limitée à 200 €.", "ue2-21", null, "calc"],
  ["Bénéfice 60 000 €, pertes antérieures 10 000 €, pas de réserve légale existante (capital 200 000 €) : bénéfice distribuable (hors report) ?", "Dotation = 5 % × 50 000 = 2 500 € ; distribuable = 60 000 − 10 000 − 2 500 = 47 500 €.", "ue2-22", null, "calc"],
  ["Capital 200 000 €, capitaux propres 90 000 € : procédure à engager ?", "90 000 < 100 000 (moitié du capital) : convocation des associés dans les 4 mois de l'approbation des comptes pour statuer sur la dissolution anticipée.", "ue2-23", null, "calc"],
  ["Capital 200 000 €, capitaux propres exactement 100 000 € : procédure de l'art. L223-42 / L225-248 ?", "Non : la procédure vise des capitaux propres inférieurs à la moitié du capital ; à 100 000 € ils lui sont égaux.", "ue2-23", null, "calc"],
  ["Pertes constatées sur l'exercice clos le 31/12/N : date limite de régularisation si la dissolution est rejetée ?", "Au plus tard à la clôture du 2e exercice suivant celui de la constatation : 31/12/N+2.", "ue2-23", null, "calc"],
  ["SARL au capital de 10 000 € en numéraire : montant minimum à libérer à la constitution ?", "1/5 = 2 000 € ; le solde dans un délai de 5 ans.", "ue2-08", null, "calc"],
  ["SAS au capital de 10 000 € en numéraire : montant minimum à libérer ?", "La moitié, soit 5 000 € ; solde dans les 5 ans.", "ue2-08", null, "calc"],
  ["SA au capital minimum de 37 000 € : montant minimum à libérer ?", "La moitié : 18 500 €.", "ue2-01", null, "calc"],
  ["SARL au capital de 40 000 € ; un apport en nature de 25 000 € : commissaire aux apports ?", "Obligatoire : l'apport (25 000 €) est inférieur à 30 000 € mais dépasse la moitié du capital (20 000 €), sauf décision unanime des associés d'y renoncer.", "ue2-07", "Seuil de 30 000 € (art. L223-9 C. com.)", "calc"],
  ["SA : 10 000 actions avec droit de vote. Quorum de l'AGO à la 1re convocation ?", "1/5 = 2 000 actions ; aucun quorum à la 2e convocation.", "ue2-16", "Art. L225-96 et L225-98 C. com. (ord. 2020-1142, en vigueur depuis le 01/01/2021)", "calc"],
  ["SA : 10 000 actions avec droit de vote. Quorum de l'AGE à la 1re, puis à la 2e convocation ?", "1/4 = 2 500 actions, puis 1/5 = 2 000 actions.", "ue2-16", "Art. L225-96 et L225-98 C. com. (ord. 2020-1142, en vigueur depuis le 01/01/2021)", "calc"],
  ["AGE de SA : 1 800 voix exprimées (abstentions exclues). Nombre de voix pour adopter une modification des statuts ?", "2/3 des voix exprimées : 1 200 voix.", "ue2-16", "Art. L225-96 et L225-98 C. com. (ord. 2020-1142, en vigueur depuis le 01/01/2021)", "calc"],
  ["SARL de 1 000 parts : seuil pour adopter une décision ordinaire, puis une modification des statuts ?", "Ordinaire : plus de la moitié des parts (501). Extraordinaire : 3/4 des parts (750).", "ue2-14", null, "calc"],
  ["Exercice clos le 31/12 : date limite d'approbation des comptes d'une SARL ? Date limite de paiement des dividendes ?", "Approbation dans les 6 mois : 30/06. Paiement des dividendes dans les 9 mois de la clôture : 30/09.", "ue2-129", null, "calc"],
  ["Une société a 12 M€ de CA, 4 M€ de total de bilan et 40 salariés : commissaire aux comptes obligatoire ?", "Non : un seul seuil est dépassé (CA > 10 M€) ; il en faut deux sur trois (5 M€ / 10 M€ / 50 salariés).", "ue2-18", "Seuils relevés par le décret n° 2024-152 du 28/02/2024 (exercices ouverts depuis le 01/01/2024) ; avant : 4 M€ / 8 M€ / 50", "calc"],
  ["Une SAS a 11 M€ de CA, 6 M€ de total de bilan et 20 salariés : commissaire aux comptes obligatoire ?", "Oui : deux seuils sont dépassés (CA > 10 M€ et bilan > 5 M€) ; mandat de 6 exercices.", "ue2-18", "Seuils relevés par le décret n° 2024-152 du 28/02/2024 (exercices ouverts depuis le 01/01/2024) ; avant : 4 M€ / 8 M€ / 50", "calc"],
  ["Augmentation de capital : 1 000 actions à 50 €, 200 actions nouvelles émises à 40 € : valeur théorique du DPS ?", "Valeur après opération = (50 × 1 000 + 40 × 200) ÷ 1 200 = 48,33 € ; DPS = 50 − 48,33 ≈ 1,67 €. Parité : 1 action nouvelle pour 5 anciennes.", "ue2-130", null, "calc"],
  ["Même opération : un actionnaire détient 50 actions anciennes. Combien d'actions nouvelles peut-il souscrire par priorité ?", "50 ÷ 5 = 10 actions nouvelles.", "ue2-130", null, "calc"],
  ["Fusion : A vaut 600 € l'action, B 800 € l'action ; B a 600 actions. Parité d'échange et actions A à créer ?", "800 ÷ 600 = 4/3 : 4 actions A contre 3 actions B ; 600 B → 800 actions A émises par l'absorbante.", "ue2-27", null, "calc"],
  ["Marque déposée à l'INPI le 15/03/2020 : date d'expiration de la protection initiale ?", "10 ans : 15/03/2030, renouvelable indéfiniment par périodes de 10 ans.", "ue2-145", null, "calc"],
  ["Abus de biens sociaux commis en 2015 et découvert en 2023 : jusqu'à quand poursuivre ?", "Délit occulte : 6 ans à compter de la découverte (2029), mais délai butoir de 12 ans après la commission (2027). Poursuites possibles jusqu'à 2027 au plus tard.", "ue2-164", "Loi n° 2017-242 du 27/02/2017", "calc"]
]);

// ===== Cartes à trous =====
DCG_CLOZE(2, [
  ["La société est un contrat par lequel les associés affectent à une entreprise commune des biens ou leur industrie en vue de partager le {{bénéfice}} ou de profiter de l'économie qui en résultera (art. {{1832}} C. civ.).", "ue2-105"],
  ["Une société acquiert la personnalité morale à son {{immatriculation}} au RCS.", "ue2-114"],
  ["La durée d'une société ne peut excéder {{99 ans}}.", "ue2-111"],
  ["Les apports peuvent être en {{numéraire}}, en {{nature}} ou en {{industrie}}.", "ue2-06"],
  ["Les apports en {{industrie}} ne concourent pas à la formation du capital social.", "ue2-06"],
  ["Une clause {{léonine}} attribue à un associé la totalité du profit ou l'exonère de toute contribution aux pertes : elle est réputée non écrite.", "ue2-107"],
  ["L'{{affectio societatis}} est la volonté de collaborer à l'entreprise commune sur un pied d'égalité.", "ue2-04"],
  ["La société en formation n'a pas la personnalité morale : les personnes qui agissent en son nom en répondent {{solidairement}}.", "ue2-113"],
  ["Le capital minimum d'une SA est de {{37 000 €}} ; celui d'une SARL ou d'une SAS est {{libre}}.", "ue2-01"],
  ["Une SA non cotée compte au moins {{2}} actionnaires, une SA cotée au moins {{7}}.", "ue2-02"],
  ["Une SARL compte de {{1 à 100}} associés, dont la responsabilité est limitée à leurs apports.", "ue2-11"],
  ["Dans une SNC, les associés ont la qualité de {{commerçants}} et répondent indéfiniment et {{solidairement}} des dettes sociales.", "ue2-09"],
  ["Dans une société civile, les associés répondent des dettes de façon {{indéfinie}} mais {{non solidaire}}.", "ue2-29"],
  ["En SCS, les {{commandités}} ont une responsabilité indéfinie et solidaire ; les {{commanditaires}} sont limités à leurs apports.", "ue2-10"],
  ["Le gérant de SARL est nécessairement une personne {{physique}}.", "ue2-11"],
  ["Les limitations de pouvoirs du gérant de SARL sont {{inopposables}} aux tiers.", "ue2-12"],
  ["Gérant {{majoritaire}} de SARL : régime des TNS ; gérant {{minoritaire}} : assimilé salarié.", "ue2-120"],
  ["En SARL, l'agrément de cession à un tiers est donné par la majorité des associés représentant au moins la {{moitié}} des parts.", "ue2-13"],
  ["En SARL, la modification des statuts exige la majorité des {{3/4}} des parts sociales.", "ue2-14"],
  ["En SARL, les comptes sont approuvés dans les {{6 mois}} de la clôture de l'exercice.", "ue2-14"],
  ["Le conseil d'administration d'une SA compte de {{3 à 18}} membres ; le directoire de {{2 à 5}} membres (7 si cotée).", "ue2-15"],
  ["Les administrateurs de SA sont nommés par l'AGO pour {{6 ans}} maximum et sont révocables {{ad nutum}}.", "ue2-122"],
  ["Le {{directoire}} dirige la SA ; le {{conseil de surveillance}} contrôle la gestion et nomme les membres du directoire.", "ue2-123"],
  ["AGO : quorum du {{1/5}} des actions à la 1re convocation ; AGE : quorum du {{1/4}} (1/5 à la 2e).", "ue2-16"],
  ["L'AGE statue à la majorité des {{2/3}} des voix exprimées.", "ue2-16"],
  ["Les {{abstentions}}, votes blancs et nuls ne sont pas comptés dans les voix exprimées.", "ue2-16"],
  ["Le président de SAS est {{obligatoire}} ; la SAS ne peut pas faire d'offre au public de titres financiers.", "ue2-19"],
  ["En SAS, la clause d'inaliénabilité est limitée à {{10 ans}}.", "ue2-127"],
  ["Une convention {{réglementée}} en SA nécessite l'autorisation préalable du conseil, un rapport spécial du CAC et l'approbation de l'AGO.", "ue2-20"],
  ["La réserve légale est dotée de {{5 %}} du bénéfice jusqu'à atteindre {{10 %}} du capital.", "ue2-21"],
  ["Bénéfice distribuable = bénéfice − pertes antérieures − {{réserve légale}} + report à nouveau bénéficiaire.", "ue2-22"],
  ["Si les capitaux propres deviennent inférieurs à la {{moitié}} du capital, les associés doivent être consultés dans les {{4 mois}} de l'approbation des comptes.", "ue2-23"],
  ["Le commissaire aux comptes est nommé pour {{6 exercices}}.", "ue2-18"],
  ["Le {{droit préférentiel de souscription}} permet de souscrire par priorité aux titres nouveaux lors d'une augmentation de capital en numéraire.", "ue2-130"],
  ["La fusion entraîne la {{transmission universelle}} du patrimoine de l'absorbée et sa dissolution sans {{liquidation}}.", "ue2-27"],
  ["Pendant la liquidation, la personnalité morale {{subsiste}} ; elle disparaît à la {{radiation}} au RCS.", "ue2-134"],
  ["Le fonds de commerce a pour élément essentiel la {{clientèle}}.", "ue2-137"],
  ["Les créanciers du vendeur d'un fonds disposent de {{10 jours}} après publication au BODACC pour faire opposition.", "ue2-139"],
  ["Le nantissement du fonds de commerce doit être inscrit au greffe dans les {{30 jours}} ; l'inscription dure {{10 ans}}.", "ue2-143"],
  ["Une marque est protégée {{10 ans}} renouvelables ; un brevet {{20 ans}} non renouvelables.", "ue2-145"],
  ["Le bail commercial a une durée minimale de {{9 ans}} (bail « 3-6-9 »).", "ue2-147"],
  ["Le bail dérogatoire a une durée maximale de {{3 ans}}.", "ue2-148"],
  ["Les actions relatives au statut des baux commerciaux se prescrivent par {{2 ans}}.", "ue2-155"],
  ["Si le bailleur refuse le renouvellement sans motif grave et légitime, il doit une indemnité d'{{éviction}}.", "ue2-150"],
  ["Le cautionnement est un contrat {{accessoire}} à la dette principale ; la garantie autonome est {{indépendante}} de celle-ci.", "ue2-158"],
  ["L'action publique se prescrit par {{1 an}} (contraventions), {{6 ans}} (délits) et {{20 ans}} (crimes).", "ue2-164"],
  ["L'abus de biens sociaux est puni de {{5 ans}} d'emprisonnement et de {{375 000 €}} d'amende.", "ue2-167"],
  ["L'amende encourue par une personne morale est égale au {{quintuple}} de celle prévue pour les personnes physiques.", "ue2-166"],
  ["Tracfin reçoit les déclarations de {{soupçon}} des professionnels assujettis à la lutte contre le blanchiment.", "ue2-172"],
  ["La loi {{Sapin II}} (2016) a créé l'AFA, la protection des lanceurs d'alerte et la CJIP.", "ue2-175"],
  ["Une infraction comporte trois éléments : {{légal}}, {{matériel}} et {{moral}}.", "ue2-165"]
]);

// ===== Méthode juridique et lexique =====
DCG_FLASH(2, [
  ["Méthode : résoudre un cas pratique de droit, quelles étapes ?", "1) Qualifier les faits (qui, quoi, quand). 2) Poser le problème de droit (la question juridique). 3) Énoncer la règle (texte, jurisprudence, avec l'article). 4) Appliquer la règle aux faits. 5) Conclure clairement.", "ue2-101", null, "ecr"],
  ["Méthode : structurer un raisonnement juridique (syllogisme) ?", "Majeure : la règle de droit. Mineure : les faits qualifiés. Conclusion : la solution. Toujours citer l'article visé (ex. art. L223-27 C. com.) et rester concis.", "ue2-101", null, "ecr"],
  ["Méthode : questions sur les décisions collectives, que vérifier en premier ?", "La forme sociale ; la nature de la décision (ordinaire, extraordinaire, unanimité) ; le quorum éventuel ; la majorité requise et les voix exprimées ; les règles propres aux statuts (SAS).", "ue2-14", null, "ecr"],
  ["Méthode : question sur la responsabilité d'un dirigeant, par où commencer ?", "Identifier le type de responsabilité (civile, pénale, procédure collective), le fait générateur (faute, infraction), le préjudice, le lien de causalité, le titulaire de l'action et le délai de prescription.", "ue2-26", null, "ecr"],
  ["Méthode : commenter un arrêt, quelles étapes ?", "Faits, procédure, problème de droit, solution de la Cour, portée de l'arrêt. Distinguer la cour d'appel de la Cour de cassation (qui juge le droit, pas les faits).", "ue2-101", null, "ecr"],
  ["Qu'est-ce que la hiérarchie des normes en droit des affaires ?", "Constitution, traités et droit de l'UE, lois et ordonnances ratifiées, règlements, décrets et arrêtés. La jurisprudence interprète et complète. Les usages et les statuts complètent à un niveau inférieur.", "ue2-101"],
  ["Qu'est-ce qu'un acte de commerce ?", "Acte défini par la loi (art. L110-1 C. com.) : achat pour revendre, entreprise de manufacture ou de transport, opérations de banque, lettre de change... On distingue les actes de commerce par nature, par la forme et par accessoire.", "ue2-102"],
  ["Quel est le statut de l'entrepreneur individuel (EI) ?", "Depuis le 15 mai 2022, l'EI a un patrimoine professionnel séparé de son patrimoine personnel : seuls les biens professionnels répondent des dettes professionnelles (sauf renonciation ou fraude).", "ue2-103"],
  ["Qu'est-ce que le boni de liquidation ?", "Solde de l'actif net après paiement des dettes, réparti entre les associés à la clôture de la liquidation.", "ue2-134"],
  ["Qu'est-ce que la nullité absolue et la nullité relative ?", "Absolue : protège l'intérêt général. Relative : protège un intérêt particulier (vices du consentement, incapacité). La nullité d'une société est encadrée (3 ans, régularisation possible).", "ue2-108"],
  ["Qu'est-ce qu'une action sociale et une action individuelle ?", "Sociale : exercée au nom de la société pour réparer son préjudice (par un associé ou le dirigeant). Individuelle : exercée par un associé ou un tiers pour réparer son préjudice personnel.", "ue2-26"],
  ["Qu'est-ce qu'une action de préférence ?", "Action conférant des droits différents des actions ordinaires (droits financiers, vote double, absence de droit de vote). Elle peut être émise par les SA et SAS.", "ue2-124"],
  ["Qu'est-ce que le BODACC ?", "Bulletin officiel des annonces civiles et commerciales : publication officielle d'actes (cessions de fonds, procédures collectives, comptes) qui fait courir les délais d'opposition des créanciers.", "ue2-139"],
  ["Qu'est-ce que le RCS ?", "Registre du commerce et des sociétés tenu par les greffes des tribunaux de commerce : l'immatriculation donne la personnalité morale aux sociétés et la qualité de commerçant aux personnes physiques.", "ue2-110"],
  ["Qu'est-ce qu'une procédure d'alerte (commissaire aux comptes) ?", "Procédure par laquelle le CAC, s'il relève des faits compromettant la continuité d'exploitation, demande des explications au dirigeant puis alerte le conseil ou les associés, et éventuellement le président du tribunal.", "ue2-18"],
  ["Qu'est-ce que la raison d'être d'une société ?", "Les valeurs ou la raison d'exister que la société se donne dans ses statuts (art. 1835 C. civ.), introduite par la loi PACTE ; distincte de la société à mission.", "ue2-112"],
  ["Qu'est-ce qu'un pacte d'associés ?", "Convention conclue entre associés, extra-statutaire (confidentielle) : clauses de préemption, sortie conjointe, non-concurrence... Il lie les seuls signataires, contrairement aux statuts, opposables à tous.", "ue2-30"],
  ["Qu'est-ce qu'une sûreté personnelle et une sûreté réelle ?", "Personnelle : engagement d'une personne (cautionnement, garantie autonome). Réelle : affectation d'un bien (gage, nantissement, hypothèque).", "ue2-159"],
  ["Qu'est-ce que le droit de suite et le droit de préférence ?", "Droit de suite : suivre le bien entre les mains du tiers acquéreur. Droit de préférence : être payé avant les autres créanciers sur le prix du bien.", "ue2-159"]
]);

// ===== QCM supplémentaires =====
window.DCG_QCM.push(
  { id: 'q-ue2-150', ue: 2, q: "Fonds de commerce cédé 250 000 € (barème 0 % jusqu'à 23 000 €, 3 % de 23 000 à 200 000 €, 5 % au-delà). Les droits d'enregistrement sont de :", choices: ["7 500 €", "7 810 €", "8 310 €", "12 500 €"], answer: 1, expl: "177 000 × 3 % + 50 000 × 5 % = 5 310 + 2 500 = 7 810 €." },
  { id: 'q-ue2-151', ue: 2, q: "Capital 100 000 €, réserve légale 9 800 €, bénéfice 30 000 € : la dotation à la réserve légale est de :", choices: ["200 €", "1 500 €", "3 000 €", "10 000 €"], answer: 0, expl: "5 % × 30 000 = 1 500 €, mais la réserve est plafonnée à 10 % du capital (10 000 €) : il ne reste que 200 € à doter." },
  { id: 'q-ue2-152', ue: 2, q: "Dans une SA de 10 000 actions avec droit de vote, quel est le quorum de l'AGE à la première convocation ?", choices: ["1 000 actions", "2 000 actions", "2 500 actions", "Aucun quorum"], answer: 2, expl: "1/4 des actions ayant le droit de vote : 2 500 actions (1/5 à la 2e convocation)." },
  { id: 'q-ue2-153', ue: 2, q: "Les capitaux propres d'une SARL au capital de 200 000 € s'élèvent à 90 000 €. Que doit faire le gérant ?", choices: ["Rien, le seuil est de 1/4 du capital", "Convoquer les associés dans les 4 mois de l'approbation des comptes pour statuer sur la dissolution", "Dissoudre immédiatement la société", "Informer uniquement le greffe"], answer: 1, expl: "90 000 € < 100 000 € (moitié du capital) : décision sur la dissolution anticipée ; à défaut, régularisation à la clôture du 2e exercice suivant." },
  { id: 'q-ue2-154', ue: 2, q: "Une SAS a 11 M€ de chiffre d'affaires, 6 M€ de total de bilan et 20 salariés. Le commissaire aux comptes est-il obligatoire ?", choices: ["Non, aucun seuil n'est atteint", "Non, il faut dépasser les 3 seuils", "Oui, deux seuils sur trois sont dépassés", "Oui, uniquement si elle est cotée"], answer: 2, expl: "Les seuils (5 M€ de bilan, 10 M€ de CA, 50 salariés) : deux sont dépassés, le CAC est obligatoire (mandat de 6 exercices)." },
  { id: 'q-ue2-155', ue: 2, q: "Quelle est la prescription de l'action publique pour un délit ?", choices: ["1 an", "3 ans", "6 ans", "20 ans"], answer: 2, expl: "1 an pour les contraventions, 6 ans pour les délits, 20 ans pour les crimes (loi du 27/02/2017)." }
);
